//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Cfg
{ 
    public enum BuffEvent
    {
        None = 0,
        /// <summary>
        /// 附加
        /// </summary>
        OnAttach = 1,
        /// <summary>
        /// 移除
        /// </summary>
        OnDettach = 2,
    }

} 
