//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Cfg
{ 
    public enum BuffAddType
    {
        /// <summary>
        /// 覆盖
        /// </summary>
        Replace = 0,
        /// <summary>
        /// 延长
        /// </summary>
        AddTime = 1,
        /// <summary>
        /// 叠加层数并且重置时间
        /// </summary>
        AddLayer1 = 2,
        /// <summary>
        /// 叠加层数并且延长时间
        /// </summary>
        AddLayer2 = 3,
    }

} 
