//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Cfg
{ 
    public enum DispelLevel
    {
        /// <summary>
        /// 弱驱散
        /// </summary>
        Basic = 0,
        /// <summary>
        /// 强驱散
        /// </summary>
        Strong = 1,
        /// <summary>
        /// 死亡驱散
        /// </summary>
        Death = 2,
    }

} 
