//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cfg
{
    /// <summary>
    /// 数值
    /// </summary>
    public enum Numeric
    {

    
        [PostMainland.Numeric("","",TypeOfValue.Permillage,false)]
        None = 0,
        /// <summary>
        /// 速度
        /// </summary>

    
        [PostMainland.Numeric("速度","速度desc",TypeOfValue.Permillage,false)]
        Speed = 1001,
        /// <summary>
        /// 攻击
        /// </summary>

    
        [PostMainland.Numeric("攻击","",TypeOfValue.Permillage,false)]
        Attack = 1002,
        /// <summary>
        /// 防御
        /// </summary>

    
        [PostMainland.Numeric("防御","",TypeOfValue.Permillage,false)]
        Defence = 1003,
        /// <summary>
        /// 生命值
        /// </summary>

    
        [PostMainland.Numeric("生命值","",TypeOfValue.Permillage,false)]
        HP = 1004,
        /// <summary>
        /// 最大生命值
        /// </summary>

    
        [PostMainland.Numeric("最大生命值","",TypeOfValue.Permillage,false)]
        MaxHP = 1005,
        /// <summary>
        /// 魔法值
        /// </summary>

    
        [PostMainland.Numeric("魔法值","",TypeOfValue.Permillage,false)]
        MP = 1006,
        /// <summary>
        /// 最大魔法值
        /// </summary>

    
        [PostMainland.Numeric("最大魔法值","",TypeOfValue.Permillage,false)]
        MaxMP = 1007,
        /// <summary>
        /// 法术强度
        /// </summary>

    
        [PostMainland.Numeric("法术强度","",TypeOfValue.Permillage,false)]
        MagicEnhance = 1008,
    }
}
