//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Cfg
{ 
    /// <summary>
    /// 数值
    /// </summary>
    public enum Numeric
    {
        None = 0,
        /// <summary>
        /// 速度
        /// </summary>
        Speed = 1001,
        /// <summary>
        /// 攻击
        /// </summary>
        Attack = 1002,
        /// <summary>
        /// 防御
        /// </summary>
        Defence = 1003,
        /// <summary>
        /// 生命值
        /// </summary>
        HP = 1004,
        /// <summary>
        /// 最大生命值
        /// </summary>
        MaxHP = 1005,
        /// <summary>
        /// 魔法值
        /// </summary>
        MP = 1006,
        /// <summary>
        /// 最大魔法值
        /// </summary>
        MAxMP = 1007,
    }

} 
