//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;


namespace Cfg
{
   
public partial class Tables
{
    public TbGlobal TbGlobal {get; }
    public TbStartProcess TbStartProcess {get; }
    public TbBuff TbBuff {get; }
    public TbSkill TbSkill {get; }

    public Tables(System.Func<string, ByteBuf> idxLoader,System.Func<string, ByteBuf> dataLoader)
    {
        var tables = new System.Collections.Generic.Dictionary<string, object>();
        TbGlobal = new TbGlobal(idxLoader("tbglobal"),"tbglobal",dataLoader); 
        tables.Add("TbGlobal", TbGlobal);
        TbStartProcess = new TbStartProcess(idxLoader("tbstartprocess"),"tbstartprocess",dataLoader); 
        tables.Add("TbStartProcess", TbStartProcess);
        TbBuff = new TbBuff(idxLoader("tbbuff"),"tbbuff",dataLoader); 
        tables.Add("TbBuff", TbBuff);
        TbSkill = new TbSkill(idxLoader("tbskill"),"tbskill",dataLoader); 
        tables.Add("TbSkill", TbSkill);

        PostInit();
        TbGlobal.CacheTables(tables); 
        TbStartProcess.CacheTables(tables); 
        TbBuff.CacheTables(tables); 
        TbSkill.CacheTables(tables); 
    }
    
    partial void PostInit();
}

}