//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;


namespace Cfg.MetaBuffEffect
{
/// <summary>
/// 附加状态
/// </summary>
public sealed partial class AttachState :  Base 
{
    public AttachState(ByteBuf _buf)  : base(_buf) 
    {
        State = (BuffState)_buf.ReadInt();
        PostInit();
    }

    public static AttachState DeserializeAttachState(ByteBuf _buf)
    {
        return new MetaBuffEffect.AttachState(_buf);
    }

    public BuffState State { get; private set; }

    public const int __ID__ = 643951239;
    public override int GetTypeId() => __ID__;

    public override void Resolve(Dictionary<string, object> _tables)
    {
        base.Resolve(_tables);
        PostResolve();
    }

    public override void TranslateText(System.Func<string, string, string> translator)
    {
        base.TranslateText(translator);
    }

    public override string ToString()
    {
        return "{ "
        + "Temp:" + Temp + ","
        + "State:" + State + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}