//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Cfg
{ 
    /// <summary>
    /// Buff状态
    /// </summary>
    public enum BuffState
    {
        None = 0,
        /// <summary>
        /// 眩晕
        /// </summary>
        Stun = 1,
        /// <summary>
        /// 缠绕
        /// </summary>
        Root = 2,
        /// <summary>
        /// 沉默
        /// </summary>
        Silence = 3,
        /// <summary>
        /// 无敌
        /// </summary>
        Invincible = 4,
        /// <summary>
        /// 隐身
        /// </summary>
        Invisible = 5,
    }

} 
