//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Cfg
{ 
    public enum DamageType
    {
        /// <summary>
        /// 纯粹伤害
        /// </summary>
        Pure = 0,
        /// <summary>
        /// 物理伤害
        /// </summary>
        Physical = 1,
        /// <summary>
        /// 物理伤害
        /// </summary>
        Magical = 2,
    }

} 
