//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cfg
{
    /// <summary>
    /// 错误码
    /// </summary>
    public enum ErrorCode
    {
        /// <summary>
        /// 网络错误
        /// </summary>
        Success = 0,
        NetworkError = 1,
        /// <summary>
        /// 账号不存在
        /// </summary>
        AccountNotExists = 1001,
        /// <summary>
        /// 密码错误
        /// </summary>
        PasswordError = 1002,
    }
}
