//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;



namespace Cfg
{

public sealed partial class StartProcess :  Bright.Config.BeanBase 
{
    public StartProcess(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        ServerType = _buf.ReadString();
        Host = _buf.ReadString();
        Port = _buf.ReadString();
        ProcessPath = _buf.ReadString();
        PostInit();
    }

    public static StartProcess DeserializeStartProcess(ByteBuf _buf)
    {
        return new StartProcess(_buf);
    }

    /// <summary>
    /// Id
    /// </summary>
    public int Id { get; private set; }
    /// <summary>
    /// 服务器类型
    /// </summary>
    public string ServerType { get; private set; }
    /// <summary>
    /// 监听地址
    /// </summary>
    public string Host { get; private set; }
    /// <summary>
    /// 监听端口
    /// </summary>
    public string Port { get; private set; }
    /// <summary>
    /// 进程路径
    /// </summary>
    public string ProcessPath { get; private set; }

    public const int __ID__ = -279645235;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, object> _tables)
    {
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "ServerType:" + ServerType + ","
        + "Host:" + Host + ","
        + "Port:" + Port + ","
        + "ProcessPath:" + ProcessPath + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}
