//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using System.Linq;

namespace Cfg
{
   
    public partial class TbGlobal
    {
        public static TbGlobal Instance { get; private set; }

        private Global _data;

        public TbGlobal (ByteBuf _buf, string _tbName, System.Func<string, ByteBuf> _loader)
        {
            Instance = this;
            ByteBuf _dataBuf = _loader(_tbName);
            int n = _buf.ReadSize();
            int m = _dataBuf.ReadSize();
            if (n != 1 || m != 1) throw new SerializationException("table mode=one, but size != 1");
            _data = Global.DeserializeGlobal(_dataBuf);
        }


        public string LoginServerAddress => _data.LoginServerAddress;

        
    
        public void CacheTables(Dictionary<string, object> _tables)
        {
            _data.Resolve(_tables);
        }
        partial void PostInit();
    }
} 