//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cfg
{
    public enum TypeOfValue
    {
        /// <summary>
        /// 绝对值
        /// </summary>
        Absolute = 0,
        /// <summary>
        /// 百分比
        /// </summary>
        Percentage = 1,
        /// <summary>
        /// 千分比
        /// </summary>
        Permillage = 2,
        /// <summary>
        /// 万分比，这个是自己创的词，字典没有
        /// </summary>
        Pertenthousandage = 3,
    }
}
