/* this is generated by nino */
namespace PostMainland
{
    public partial class C2L_Login
    {
        public static C2L_Login.SerializationHelper NinoSerializationHelper = new C2L_Login.SerializationHelper();
        public class SerializationHelper: Nino.Serialization.NinoWrapperBase<C2L_Login>
        {
            #region NINO_CODEGEN
            public override void Serialize(C2L_Login value, Nino.Serialization.Writer writer)
            {
                writer.Write(value.Account);
                writer.Write(value.Password);
                writer.CompressAndWrite(value.RpcId);
            }

            public override C2L_Login Deserialize(Nino.Serialization.Reader reader)
            {
                C2L_Login value = new C2L_Login();
                value.Account = reader.ReadString();
                value.Password = reader.ReadString();
                value.RpcId =  (System.Int32)reader.DecompressAndReadNumber();
                return value;
            }
            #endregion
        }
    }
}