/* this is generated by nino */
namespace PostMainland
{
    public partial class SC_LoginAck
    {
        public static SC_LoginAck.SerializationHelper NinoSerializationHelper = new SC_LoginAck.SerializationHelper();
        public class SerializationHelper: Nino.Serialization.NinoWrapperBase<SC_LoginAck>
        {
            #region NINO_CODEGEN
            public override void Serialize(SC_LoginAck value, Nino.Serialization.Writer writer)
            {
                writer.Write(value.Account);
                writer.Write(value.Name);
                writer.CompressAndWrite(value.Status);
                writer.CompressAndWrite(value.Error);
                writer.Write(value.Message);
            }

            public override SC_LoginAck Deserialize(Nino.Serialization.Reader reader)
            {
                SC_LoginAck value = new SC_LoginAck();
                value.Account = reader.ReadString();
                value.Name = reader.ReadString();
                value.Status =  (System.Int32)reader.DecompressAndReadNumber();
                value.Error =  (System.Int32)reader.DecompressAndReadNumber();
                value.Message = reader.ReadString();
                return value;
            }
            #endregion
        }
    }
}