/* this is generated by nino */
namespace PostMainland
{
    public partial class C2S_Connect
    {
        public static C2S_Connect.SerializationHelper NinoSerializationHelper = new C2S_Connect.SerializationHelper();
        public class SerializationHelper: Nino.Serialization.NinoWrapperBase<C2S_Connect>
        {
            #region NINO_CODEGEN
            public override void Serialize(C2S_Connect value, Nino.Serialization.Writer writer)
            {
                writer.CompressAndWrite(value.RpcId);
            }

            public override C2S_Connect Deserialize(Nino.Serialization.Reader reader)
            {
                C2S_Connect value = new C2S_Connect();
                value.RpcId =  (System.Int32)reader.DecompressAndReadNumber();
                return value;
            }
            #endregion
        }
    }
}