/* this is generated by nino */
namespace PostMainland
{
    public partial class S2C_Login
    {
        public static S2C_Login.SerializationHelper NinoSerializationHelper = new S2C_Login.SerializationHelper();
        public class SerializationHelper: Nino.Serialization.NinoWrapperBase<S2C_Login>
        {
            #region NINO_CODEGEN
            public override void Serialize(S2C_Login value, Nino.Serialization.Writer writer)
            {
                writer.Write(value.Name);
                writer.CompressAndWrite(value.RpcId);
                writer.CompressAndWrite(value.Error);
                writer.Write(value.Message);
            }

            public override S2C_Login Deserialize(Nino.Serialization.Reader reader)
            {
                S2C_Login value = new S2C_Login();
                value.Name = reader.ReadString();
                value.RpcId =  (System.Int32)reader.DecompressAndReadNumber();
                value.Error =  (System.Int32)reader.DecompressAndReadNumber();
                value.Message = reader.ReadString();
                return value;
            }
            #endregion
        }
    }
}