/* this is generated by nino */
namespace PostMainland
{
    public partial class C2S_Disconnect
    {
        public static C2S_Disconnect.SerializationHelper NinoSerializationHelper = new C2S_Disconnect.SerializationHelper();
        public class SerializationHelper: Nino.Serialization.NinoWrapperBase<C2S_Disconnect>
        {
            #region NINO_CODEGEN
            public override void Serialize(C2S_Disconnect value, Nino.Serialization.Writer writer)
            {
                writer.CompressAndWrite(value.RpcId);
            }

            public override C2S_Disconnect Deserialize(Nino.Serialization.Reader reader)
            {
                C2S_Disconnect value = new C2S_Disconnect();
                value.RpcId =  (System.Int32)reader.DecompressAndReadNumber();
                return value;
            }
            #endregion
        }
    }
}