/* this is generated by nino */
namespace PostMainland
{
    public partial class S2C_ConnectAck
    {
        public static S2C_ConnectAck.SerializationHelper NinoSerializationHelper = new S2C_ConnectAck.SerializationHelper();
        public class SerializationHelper: Nino.Serialization.NinoWrapperBase<S2C_ConnectAck>
        {
            #region NINO_CODEGEN
            public override void Serialize(S2C_ConnectAck value, Nino.Serialization.Writer writer)
            {
                writer.CompressAndWrite(value.RpcId);
                writer.CompressAndWrite(value.Error);
                writer.Write(value.Message);
            }

            public override S2C_ConnectAck Deserialize(Nino.Serialization.Reader reader)
            {
                S2C_ConnectAck value = new S2C_ConnectAck();
                value.RpcId =  (System.Int32)reader.DecompressAndReadNumber();
                value.Error =  (System.Int32)reader.DecompressAndReadNumber();
                value.Message = reader.ReadString();
                return value;
            }
            #endregion
        }
    }
}