/* this is generated by nino */
namespace PostMainland
{
    public partial class CS_Login
    {
        public static CS_Login.SerializationHelper NinoSerializationHelper = new CS_Login.SerializationHelper();
        public class SerializationHelper: Nino.Serialization.NinoWrapperBase<CS_Login>
        {
            #region NINO_CODEGEN
            public override void Serialize(CS_Login value, Nino.Serialization.Writer writer)
            {
                writer.Write(value.Account);
                writer.Write(value.Password);
                writer.CompressAndWrite(value.RpcId);
            }

            public override CS_Login Deserialize(Nino.Serialization.Reader reader)
            {
                CS_Login value = new CS_Login();
                value.Account = reader.ReadString();
                value.Password = reader.ReadString();
                value.RpcId =  (System.Int32)reader.DecompressAndReadNumber();
                return value;
            }
            #endregion
        }
    }
}