/* this is generated by nino */
namespace PostMainland
{
    public partial class S2C_Notify
    {
        public static S2C_Notify.SerializationHelper NinoSerializationHelper = new S2C_Notify.SerializationHelper();
        public class SerializationHelper: Nino.Serialization.NinoWrapperBase<S2C_Notify>
        {
            #region NINO_CODEGEN
            public override void Serialize(S2C_Notify value, Nino.Serialization.Writer writer)
            {
                writer.CompressAndWriteEnum(typeof(System.Int32), (ulong) value.MessageType);
                writer.Write(value.Message);
            }

            public override S2C_Notify Deserialize(Nino.Serialization.Reader reader)
            {
                S2C_Notify value = new S2C_Notify();
                value.MessageType = (TouchSocket.Core.Log.LogType)reader.DecompressAndReadEnum(typeof(System.Int32));
                value.Message = reader.ReadString();
                return value;
            }
            #endregion
        }
    }
}