/* this is generated by nino */
namespace PostMainland
{
    public partial class C2S_Login
    {
        public static C2S_Login.SerializationHelper NinoSerializationHelper = new C2S_Login.SerializationHelper();
        public class SerializationHelper: Nino.Serialization.NinoWrapperBase<C2S_Login>
        {
            #region NINO_CODEGEN
            public override void Serialize(C2S_Login value, Nino.Serialization.Writer writer)
            {
                writer.Write(value.Account);
                writer.Write(value.Password);
                writer.CompressAndWrite(value.RpcId);
            }

            public override C2S_Login Deserialize(Nino.Serialization.Reader reader)
            {
                C2S_Login value = new C2S_Login();
                value.Account = reader.ReadString();
                value.Password = reader.ReadString();
                value.RpcId =  (System.Int32)reader.DecompressAndReadNumber();
                return value;
            }
            #endregion
        }
    }
}