/* this is generated by nino */
namespace PostMainland
{
    public partial class S2G_Test
    {
        public static S2G_Test.SerializationHelper NinoSerializationHelper = new S2G_Test.SerializationHelper();
        public class SerializationHelper: Nino.Serialization.NinoWrapperBase<S2G_Test>
        {
            #region NINO_CODEGEN
            public override void Serialize(S2G_Test value, Nino.Serialization.Writer writer)
            {
                writer.Write(value.Message);
            }

            public override S2G_Test Deserialize(Nino.Serialization.Reader reader)
            {
                S2G_Test value = new S2G_Test();
                value.Message = reader.ReadString();
                return value;
            }
            #endregion
        }
    }
}