//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;



namespace Cfg.MetaBuffTrigger
{ 

public sealed partial class Repeat :  Base 
{
    public Repeat(JSONNode _json)  : base(_json) 
    {
        { if(!_json["interval_ms"].IsNumber) { throw new SerializationException(); }  IntervalMs = _json["interval_ms"]; }
        PostInit();
    }

    public Repeat(int interval_ms )  : base() 
    {
        this.IntervalMs = interval_ms;
        PostInit();
    }

    public static Repeat DeserializeRepeat(JSONNode _json)
    {
        return new MetaBuffTrigger.Repeat(_json);
    }

    /// <summary>
    /// 毫秒
    /// </summary>
    public int IntervalMs { get; private set; }

    public const int __ID__ = 186745065;
    public override int GetTypeId() => __ID__;

    public override void Resolve(Dictionary<string, object> _tables)
    {
        base.Resolve(_tables);
        PostResolve();
    }

    public override void TranslateText(System.Func<string, string, string> translator)
    {
        base.TranslateText(translator);
    }

    public override string ToString()
    {
        return "{ "
        + "IntervalMs:" + IntervalMs + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}
}
