//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;



namespace Cfg
{ 

public sealed partial class EC_Buff :  Bright.Config.BeanBase 
{
    public EC_Buff(JSONNode _json) 
    {
        { if(!_json["id"].IsNumber) { throw new SerializationException(); }  Id = _json["id"]; }
        { if(!_json["name"].IsString) { throw new SerializationException(); }  Name = _json["name"]; }
        { if(!_json["desc"].IsString) { throw new SerializationException(); }  Desc = _json["desc"]; }
        { if(!_json["dispel_level"].IsNumber) { throw new SerializationException(); }  DispelLevel = (DispelLevel)_json["dispel_level"].AsInt; }
        { if(!_json["duration_ms"].IsNumber) { throw new SerializationException(); }  DurationMs = _json["duration_ms"]; }
        { if(!_json["add_type"].IsNumber) { throw new SerializationException(); }  AddType = (BuffAddType)_json["add_type"].AsInt; }
        { if(!_json["add_layer"].IsNumber) { throw new SerializationException(); }  AddLayer = _json["add_layer"]; }
        { var __json0 = _json["meta_buffs"]; if(!__json0.IsArray) { throw new SerializationException(); } MetaBuffs = new System.Collections.Generic.List<MetaBuff>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { MetaBuff __v0;  { if(!__e0.IsObject) { throw new SerializationException(); }  __v0 = MetaBuff.DeserializeMetaBuff(__e0);  }  MetaBuffs.Add(__v0); }   }
        PostInit();
    }

    public EC_Buff(int id, string name, string desc, DispelLevel dispel_level, int duration_ms, BuffAddType add_type, int add_layer, System.Collections.Generic.List<MetaBuff> meta_buffs ) 
    {
        this.Id = id;
        this.Name = name;
        this.Desc = desc;
        this.DispelLevel = dispel_level;
        this.DurationMs = duration_ms;
        this.AddType = add_type;
        this.AddLayer = add_layer;
        this.MetaBuffs = meta_buffs;
        PostInit();
    }

    public static EC_Buff DeserializeEC_Buff(JSONNode _json)
    {
        return new EC_Buff(_json);
    }

    /// <summary>
    /// id，5+2位
    /// </summary>
    public int Id { get; private set; }
    /// <summary>
    /// 名字
    /// </summary>
    public string Name { get; private set; }
    /// <summary>
    /// 描述
    /// </summary>
    public string Desc { get; private set; }
    /// <summary>
    /// 驱散等级
    /// </summary>
    public DispelLevel DispelLevel { get; private set; }
    /// <summary>
    /// 持续时间_毫秒,0就是瞬时
    /// </summary>
    public int DurationMs { get; private set; }
    /// <summary>
    /// 叠加方式
    /// </summary>
    public BuffAddType AddType { get; private set; }
    /// <summary>
    /// 叠加层数
    /// </summary>
    public int AddLayer { get; private set; }
    public System.Collections.Generic.List<MetaBuff> MetaBuffs { get; private set; }

    public const int __ID__ = -1178785932;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, object> _tables)
    {
        foreach(var _e in MetaBuffs) { _e?.Resolve(_tables); }
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
        foreach(var _e in MetaBuffs) { _e?.TranslateText(translator); }
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "Name:" + Name + ","
        + "Desc:" + Desc + ","
        + "DispelLevel:" + DispelLevel + ","
        + "DurationMs:" + DurationMs + ","
        + "AddType:" + AddType + ","
        + "AddLayer:" + AddLayer + ","
        + "MetaBuffs:" + Bright.Common.StringUtil.CollectionToString(MetaBuffs) + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}
}
