//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;



namespace Cfg
{ 

public sealed partial class Global :  Bright.Config.BeanBase 
{
    public Global(JSONNode _json) 
    {
        { if(!_json["login_server_address"].IsString) { throw new SerializationException(); }  LoginServerAddress = _json["login_server_address"]; }
        PostInit();
    }

    public Global(string login_server_address ) 
    {
        this.LoginServerAddress = login_server_address;
        PostInit();
    }

    public static Global DeserializeGlobal(JSONNode _json)
    {
        return new Global(_json);
    }

    public string LoginServerAddress { get; private set; }

    public const int __ID__ = 2135814083;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, object> _tables)
    {
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "LoginServerAddress:" + LoginServerAddress + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}
}
