//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using SimpleJSON;


namespace Cfg
{ 
   
public sealed partial class Tables
{
    public TbGlobal TbGlobal {get; }
    public TbStartProcess TbStartProcess {get; }
    public TbDatabase TbDatabase {get; }
    public TbBuff TbBuff {get; }
    public TbSkill TbSkill {get; }

    public Tables(System.Func<string, JSONNode> loader)
    {
        var tables = new System.Collections.Generic.Dictionary<string, object>();
        TbGlobal = new TbGlobal(loader("tbglobal")); 
        tables.Add("TbGlobal", TbGlobal);
        TbStartProcess = new TbStartProcess(loader("tbstartprocess")); 
        tables.Add("TbStartProcess", TbStartProcess);
        TbDatabase = new TbDatabase(loader("tbdatabase")); 
        tables.Add("TbDatabase", TbDatabase);
        TbBuff = new TbBuff(loader("tbbuff")); 
        tables.Add("TbBuff", TbBuff);
        TbSkill = new TbSkill(loader("tbskill")); 
        tables.Add("TbSkill", TbSkill);
        PostInit();

        TbGlobal.Resolve(tables); 
        TbStartProcess.Resolve(tables); 
        TbDatabase.Resolve(tables); 
        TbBuff.Resolve(tables); 
        TbSkill.Resolve(tables); 
        PostResolve();
    }

    public void TranslateText(System.Func<string, string, string> translator)
    {
        TbGlobal.TranslateText(translator); 
        TbStartProcess.TranslateText(translator); 
        TbDatabase.TranslateText(translator); 
        TbBuff.TranslateText(translator); 
        TbSkill.TranslateText(translator); 
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}