//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;



namespace Cfg
{ 

public sealed partial class TbStartProcess
{
    private readonly Dictionary<int, StartProcess> _dataMap;
    private readonly List<StartProcess> _dataList;
    
    public TbStartProcess(JSONNode _json)
    {
        _dataMap = new Dictionary<int, StartProcess>();
        _dataList = new List<StartProcess>();
        
        foreach(JSONNode _row in _json.Children)
        {
            var _v = StartProcess.DeserializeStartProcess(_row);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
        PostInit();
    }

    public Dictionary<int, StartProcess> DataMap => _dataMap;
    public List<StartProcess> DataList => _dataList;

    public StartProcess GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public StartProcess Get(int key) => _dataMap[key];
    public StartProcess this[int key] => _dataMap[key];

    public void Resolve(Dictionary<string, object> _tables)
    {
        foreach(var v in _dataList)
        {
            v.Resolve(_tables);
        }
        PostResolve();
    }

    public void TranslateText(System.Func<string, string, string> translator)
    {
        foreach(var v in _dataList)
        {
            v.TranslateText(translator);
        }
    }
    
    
    partial void PostInit();
    partial void PostResolve();
}

}